name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'
          distribution: 'graalvm-community'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: landing-page/src/main/webui/package-lock.json
      - name: Restore Maven cache
        uses: skjolber/maven-cache-github-action@v2.0
        with:
          step: restore
      - name: Build native package
        run: ./mvnw --pl landing-page -Pnative package
      - name: Save Maven cache
        uses: skjolber/maven-cache-github-action@v2.0
        with:
          step: save